### Site Settings ###
title               : Healthcare Data Scientist
description         : Fort d'une solide expérience en gestion et analyse des données, mes compétences en résolution de problèmes et en gestion de tâches administratives et opérationnelles sont excellentes. De plus, mon leadership naturel me permet de motiver et de diriger les équipes avec efficacité.
baseurl             : "/saadomar"            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : SAAD-DJIB/saadomar.github.io      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : SAAD-DJIB/saadomar.github.io
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : OMAR Saad
  image             : https://thumbs2.imgbox.com/a7/2f/EjSXAQvx_t.jpg
# behance           : your_username
# dribbble          : your_username
  email             : saad.oamr.abdillahi@hotmail.com
  facebook          : saad.o.saad
  github            : SAAD-DJIB
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : saad-omar-abdillahi-27a0a8122/
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name



### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
